.github/dependabot.yml

This adds dependabot integration for keeping dependencies up to date.

[CI/CD] Dependabot Integration

---

.github/dependabot.yml

This fixes the dependabot time format issue.

[Small] Dependabot Time Formate

---

Makefile

This adds `coverage` to .PHONY

[Small] Add coverage to .Phony

---

Makefile
README.md
build.gradle.kts
src/main/kotlin/ModelForge.kt
src/main/kotlin/providers/IntegerProvider.kt
src/test/kotlin/ModelForgeTest.kt
src/test/kotlin/providers/IntegerProviderTest.kt

This introduces an integer provider and closes #3

[Feature] Integer Provider

---

src/test/kotlin/ModelForgeTest.kt

This adds a missing test to validate that unsupported types throw an exception.

[Small] Model Forge Exception Test

---

README.md
src/main/kotlin/ModelForge.kt
src/main/kotlin/providers/LongProvider.kt
src/test/kotlin/ModelForgeTest.kt
src/test/kotlin/providers/LongProviderTest.kt

This adds support for auto generating Long values. This closes #21

[Feature] Long Provider

---

README.md
src/main/kotlin/ModelForge.kt
src/main/kotlin/providers/DoubleProvider.kt
src/test/kotlin/ModelForgeTest.kt
src/test/kotlin/providers/DoubleProviderTest.kt

This introduces auto generation for doubles and closes #4

[Feature] Double Provider

---

src/main/kotlin/providers/IntegerProvider.kt
src/main/kotlin/providers/LongProvider.kt
src/test/kotlin/providers/IntegerProviderTest.kt
src/test/kotlin/providers/LongProviderTest.kt

This makes use of the kotlin random in order to easily get randoms within a given range.

[Enhancement] Kotlin Random

---

README.md
src/main/kotlin/ModelForge.kt
src/main/kotlin/providers/FloatProvider.kt
src/test/kotlin/ModelForgeTest.kt
src/test/kotlin/providers/FloatProviderTest.kt

This adds auto generation for float types and closes #20

[Feature] Float Provider

---

README.md
src/main/kotlin/ModelForge.kt
src/main/kotlin/providers/BooleanProvider.kt
src/test/kotlin/ModelForgeTest.kt
src/test/kotlin/providers/BooleanProviderTest.kt

This adds auto generation for booleans and closes #5

[Feature] Boolean Provider

---

README.md
build.gradle.kts
src/main/kotlin/ModelForge.kt
src/main/kotlin/providers/DateProvider.kt
src/test/kotlin/ModelForgeTest.kt
src/test/kotlin/providers/DateProviderTest.kt

This adds auto generated dates and closes #6

[Feature] Date Provider

---

build.gradle.kts
src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
src/main/kotlin/io/github/hellocuriosity/ModelForgeException.kt
src/main/kotlin/io/github/hellocuriosity/providers/BooleanProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/DateProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/DoubleProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/FloatProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/IntegerProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/LongProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/Provider.kt
src/main/kotlin/io/github/hellocuriosity/providers/StringProvider.kt
src/test/kotlin/io/github/hellocuriosity/ModelForgeExceptionTest.kt
src/test/kotlin/io/github/hellocuriosity/ModelForgeTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/BooleanProviderTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/DateProviderTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/DoubleProviderTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/FloatProviderTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/IntegerProviderTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/LongProviderTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/StringProviderTest.kt

This repackages the src under `io.github.hellocuriosity` and changes the group id as well.

[Housekeeping] Proper Packaging

---

README.md

[Small] Remove Ko-Fi Badge

---

CHANGELOG.MD
build.gradle.kts

[Release] Prepare Version 0.1.0

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

This enables java 8 compatibility.

[Small] Enable Java 8 Compatibility

---

README.md

This adds maven central badge to the readme.

[Documentation] Maven Central Badge

---

.github/workflows/main.yml

This should enable pull requests to run on forks as well. Specifically, uploading coverage reports.

[Small] Run PRs on Forks

---

.github/workflows/main.yml
CHANGELOG.MD
README.md

This updates the `README` and `CHANGELOG` to reflect the new hotness in the upcoming 0.2.0 release 🔥

[Release] Prepare Version 0.2.0

---

CONTRIBUTUNG.md
README.md

This updates the README and CONTRIBUTION documentation.

[Documentation] Readme/Contribution Update

---

README.md

Use library name over repository name.

[Small] Use Library Name

---

scripts/publish.sh

[Small] Tag Retrieval

---

CHANGELOG.MD
README.md
src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
src/main/kotlin/io/github/hellocuriosity/providers/CalendarProvider.kt
src/test/kotlin/io/github/hellocuriosity/TestObject.kt
src/test/kotlin/io/github/hellocuriosity/providers/CalendarProviderTest.kt
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This adds auto generation for calendars and closes #30

[Feature] Calendar Provider

---

CHANGELOG.MD
README.md
src/main/kotlin/io/github/hellocuriosity/Millis.kt
src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
src/main/kotlin/io/github/hellocuriosity/providers/CalendarProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/DateProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/InstantProvider.kt
src/test/kotlin/io/github/hellocuriosity/TestObject.kt
src/test/kotlin/io/github/hellocuriosity/providers/DateProviderTest.kt
src/test/kotlin/io/github/hellocuriosity/providers/InstantProviderTest.kt

This adds auto generations for `Instant` and closes #31

[Feature] Instant Provider

---

src/main/kotlin/io/github/hellocuriosity/providers/BooleanProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/DateProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/DoubleProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/FloatProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/IntegerProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/LongProvider.kt
src/main/kotlin/io/github/hellocuriosity/providers/StringProvider.kt

This adds the missing java docs to the providers.

Missing java docs

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.3.0

---

CHANGELOG.MD
README.md
src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
src/main/kotlin/io/github/hellocuriosity/providers/EnumProvider.kt
src/test/kotlin/io/github/hellocuriosity/TestObject.kt
src/test/kotlin/io/github/hellocuriosity/providers/EnumProviderTest.kt

This adds auto generations for enums and closes #7

[Feature] Enum Provider

---

build.gradle.kts

This drops the last jcenter dependencies 🚀

[Housekeeping] Drop jcenter Dependencies

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.4.0

---

CHANGELOG.MD
README.md
src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
src/main/kotlin/io/github/hellocuriosity/ModelForgeKotlin.kt
src/main/kotlin/io/github/hellocuriosity/providers/Provider.kt
src/test/kotlin/io/github/hellocuriosity/ModelForgeKotlinTest.kt
src/test/kotlin/io/github/hellocuriosity/ModelForgeTest.kt
src/test/kotlin/io/github/hellocuriosity/TestProviderObject.kt

This adds support for custom providers and closes #8

[Feature] Custom Provider Support

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.5.0

---

build.gradle.kts

Jvm Target to help support Android

Jvm Target 1.6

---

CHANGELOG.MD
README.md

Missing documentation from optional support changes

[Release] Version 0.5.1

---

CHANGELOG.MD
README.md
src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
src/main/kotlin/io/github/hellocuriosity/providers/FileProvider.kt
src/test/kotlin/io/github/hellocuriosity/TestObject.kt
src/test/kotlin/io/github/hellocuriosity/providers/FileProviderTest.kt

This adds auto generations for files

[Feature] File Provider

---

src/test/kotlin/io/github/hellocuriosity/TestObject.kt

This adds additional validation for enums that take a value.

[Testing] Enum Class with Values

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.6.0

---

src/main/kotlin/io/github/hellocuriosity/ModelForgeKotlin.kt
src/test/kotlin/io/github/hellocuriosity/ModelForgeKotlinTest.kt

Added reified inline extension functions to ModelForge

Add reified inline build extension functions

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.7.0

---

.github/workflows/main.yml

This bumps the codecov action to v1.5.2

[Small] Codecov Action Version

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.7.1

---

.editorconfig

This adds an `.editorconfig` to the project.

[Format] Editor Config

---

.gitignore
README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/Forgery.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ForgeryTest.kt

Get in that Kotlin groove while adding `Provider`s 👯 
RT(F)M 😉

Addd more Kotlin Provider<T> fanciness

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.7.2

---

.github/dependabot.yml

This enables `GitHub Action` dependency updates via `dependabot`

[Enhancement] Enable GitHub Action Dependency Updates

---

CHANGELOG.MD
README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/UuidProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/UuidProviderTest.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt

This adds auto generations for UUIDs

[Feature] UUID Provider

---

CHANGELOG.MD
README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/ByteProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/ByteProviderTest.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt

This adds auto generations for `Byte`s and resolves #123

[Feature] Byte Provider

---

CHANGELOG.MD
README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/CharProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/CharProviderTest.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt

This adds auto generations for `Char`s and resolves #124

[Feature] Char Provider

---

README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/Forgery.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForgeKotlin.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ForgeryTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ModelForgeKotlinTest.kt

This updates the forgery extensions and extends functionality to `Set`s

[Enhancement] Forgery Extensions

---

CHANGELOG.MD
README.md

[Release] Prepare Version 0.8.0

---

build.gradle.kts

This cleans up the detekt configuration and removes the deprecated warnings.

[Housekeeping] Detekt Config

---

.github/workflows/main.yml
.github/workflows/publish.yml

This runs the CI with the Temuring SDK

[Housekeeping] Run CI with Temurin SDK

---

forge-core/build.gradle.kts
forge-core/src/test/kotlin/io/github/hellocuriosity/ForgeryTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ModelForgeKotlinTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ModelForgeTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/BooleanProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/CalendarProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/DateProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/DoubleProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/EnumProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/FileProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/FloatProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/InstantProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/IntegerProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/LongProviderTest.kt

This removes `Mockito` in favor of `MockK` and closes #134. It also cleans up the test method naming 🏕️ 

[Enhancement] MockK Integration

---

.github/workflows/main.yml

This extends the CI to run against multiple `Java` SDKs.

[CI/CD] Run with Java Matrix

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This adds two issue templates for reporting bugs and requesting new features.

[Enhancement] Issue Template

---

.github/ISSUE_TEMPLATE/feature_request.md

This removes the incorrect markdown from the feature issue template.

[Fix] Feature Issue Template

---

forge-core/src/main/kotlin/io/github/hellocuriosity/providers/ByteProvider.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/DoubleProvider.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/FloatProvider.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/IntegerProvider.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/LongProvider.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/ShortProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/ByteProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/DoubleProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/FloatProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/IntegerProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/LongProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/ShortProviderTest.kt

This removes the custom `min` and `max` , and utilizes the build in kotlin constants.

[Housekeeping] Number Defaults

---

.github/ISSUE_TEMPLATE/bug_report.md

This reorganizes the bug issue template to make more sense (at least to me) 😅 Observed behavoir first and then the expected. It feels like the right way and adds the extra layer of context 🚀 

[Enhancement] Bug Issue Template

---

forge-core/src/test/kotlin/io/github/hellocuriosity/providers/ByteProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/IntegerProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/LongProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/ShortProviderTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/StringProviderTest.kt

This cleans up the remaining test names with `_`.

[Housekeeping] Clean Up Test Names

---

forge-core/build.gradle.kts

Publish sources, resolves #161

Publish sources, solves #161

---

CHANGELOG.MD
MIGRATION.md
README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/Forgery.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForgeKotlin.kt

[Release] Prepare Version 0.9.0

---

buildSrc/src/main/kotlin/Dependencies.kt

[Dependency] Kotlin 1.6.20

---

gradle/wrapper/gradle-wrapper.properties

[Dependency] Gradle Wrapper 7.4.2

---

buildSrc/src/main/kotlin/Dependencies.kt

Bump kotlinter to version 3.10.0

[Dependency] Kotlinter 3.10.0

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps detekt to version 1.20.0

[Dependency] Bump Detekt to Version 1.20.0

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps Mockk to version 1.12.4

[Dependency] Bump Mockk to Version 1.12.4

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps Kotlin to version 1.7.10

[Dependency] Bump Kotlin to Version 1.7.10

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps kover to version 0.5.1

[Dependency] Bump Kover to Version 0.5.1

---

buildSrc/src/main/kotlin/Dependencies.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/CharProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ForgeryTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ModelForgeKotlinTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ModelForgeTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/TestProviderObject.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/EnumProviderTest.kt

This bumps kotlinter to version 3.11.1

[Dependency] Bump Kotlinter to Version 3.11.1

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
README.md

This adds a long over due code of conduct 🙌

[Documentation] Code of Conduct

---

README.md

This adds the awesome kotlin badge, now that the forge is represented there.

[Documentation] Awesome Kotlin Badge

---

forge-core/src/main/kotlin/io/github/hellocuriosity/Forgery.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForgeKotlin.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ForgeryTest.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/ModelForgeKotlinTest.kt

This removes the `deprecated` functions in preparation for version `1.0.0`.

[Housekeeping] Remove Deprecated Functions

---

.github/workflows/auto-release.yml
CHANGELOG.MD
MIGRATION.md
Makefile

This fixes the auto release not being triggered. If the CI runs successfully then the release will be triggered upon merging.

[CI/CD] Fix Auto Release Trigger

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps Kotlin to version 1.7.20

[Dependency] Bump Kotlin to Version 1.7.20

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps mockk to version 1.13.2

[Dependency] Bump Mockk to Version 1.13.2

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps objenesis to version 3.3

[Dependency] Bump Objenesis to Version 3.3

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps detekt to version 1.21.0

[Dependency] Bump Detekt to Version 1.21.0

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps jupiter to version 3.3

[Dependency] Bump Jupiter to Version 5.9.1

---

buildSrc/src/main/kotlin/Dependencies.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/GetEnum.kt

This bumps kotlinter to version 3.12.0

[Dependency] Bump Kotlinter to Version 3.12.0

---

buildSrc/build.gradle.kts

This cleans up the terminal warnings for the buildSrc plugin

[Housekeeping] BuildSrc Gradle Warnings

---

.codecov.yml
build.gradle.kts

This updates the kover configuration to use the `intellij engine`, which picks up coverage on inline/reified functions.

[Housekeeping] Kover IntelliJ Engine

---

CHANGELOG.MD
README.md

This is the official `1.1.0` release.

[Release] Version 1.1.0

---

forge-core/src/test/kotlin/io/github/hellocuriosity/ModelForgeTest.kt

This adds missing tests for auto-generating sets.

[Testing] Add Missing Set Tests

---

website/docs/changelog.md

This adds missing information for version `1.1.1`.

[Mini] Update Changelog Version 1.1.1

---

README.md
website/docs/changelog.md
website/docs/getting-started/gradle-dependency.md

This fixes the documentation to have the correct version number `1.2.0`

[Documentation] Fix Version Number

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps Ben Manes Versions to `0.44.0`

[Dependency] Bump Ben Manes Versions to 0.44.0

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps detekt to version `1.22.0`

[Dependency] Bump Detekt to 1.22.0

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps jupiter to version `5.9.2`

[Dependency] Bump jupiter to 5.9.2

---

buildSrc/src/main/kotlin/Dependencies.kt

This bumps Mockk to version `1.13.4`

[Dependency] Bump Mockk to 1.13.4

---

.github/workflows/verify-doc.yml
Makefile
scripts/create-release.sh
scripts/get_next_version.sh
scripts/verify-doc.sh

[CI/CD] Readme / Change-log Action Verification

---

.github/workflows/verify-doc.yml
README.md
website/docs/changelog.md

Official release version 1.3.0

[Release] Version 1.3.0

---

website/docs/getting-started/gradle-dependency.md

This bumps the dependency to the proper version in the website documentation.

[Documentation] Point to Proper Dependency

---

README.md
website/docs/changelog.md
website/docs/getting-started/gradle-dependency.md

This prepares the release for version `1.4.0`.

[Prepare] Release Version 1.4.0

---

renovate.json

This adds the `dependencies` label to renovate PRs.

[Housekeeping] Renovate Labeling

---

README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/UIntProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/UIntProviderTest.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt
website/docs/supported-types/uint.md
website/docs/supported-types/uuid.md

This adds auto-generation for `UInt`s.

[Feature] UInt Provider

---

website/docs/introduction.md

This updates the website introduction to point to where the UInt provider support can be found.

[Documentation] Add UInt to Introduction

---

forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt

This actually makes use of the new shinny `UIntProvider` 🙈 

[Fix] Use UIntProvider

---

website/docs/supported-types/uint.md

This unifies the description to align with the other types' descriptions.

[Documentation] Unify UIntProvider Description

---

.github/PULL_REQUEST_TEMPLATE.md

This adds info to update the `README,` and the website documentation.

[Documentation] Update Pull Request Template

---

README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/UByteProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/UByteProviderTest.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/Assert.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt
website/docs/introduction.md
website/docs/supported-types/ubyte.md
website/docs/supported-types/uint.md
website/docs/supported-types/uuid.md

This adds auto-generation for `UByte`s.

[Feature] UByte Provider

---

Makefile

This polishes up the `Makefile`
- [-] Update [README](../README.md) (where applicable)
- [-] Update [Documentation](../website/docs/introduction.md) (where applicable)

[Housekeeping] Makefile Clean Up

---

forge-core/src/test/kotlin/io/github/hellocuriosity/providers/UIntProviderTest.kt

🙈 
- [-] Update [README](../README.md) (where applicable)
- [-] Update [Documentation](../website/docs/introduction.md) (where applicable)

[Housekeeping] Remove Unused Mocks in UIntProviderTest

---

README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/ULongProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/ULongProviderTest.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/Assert.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt
website/docs/introduction.md
website/docs/supported-types/ulong.md
website/docs/supported-types/uuid.md

This adds auto-generation for `ULong`s.

[Feature] ULong Provider

---

forge-core/src/main/kotlin/io/github/hellocuriosity/providers/UByteProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/UByteProviderTest.kt

This adds a test to verify that the `UIntProvider` is called in the `UByteProvider`.
- [-] Update [README](../README.md) (where applicable)
- [-] Update [Documentation](../website/docs/introduction.md) (where applicable)

[Testing} UByte Mock Provider

---

forge-core/src/test/kotlin/io/github/hellocuriosity/providers/UByteProviderTest.kt

Use kotlin test annotation.
- [-] Update [README](../README.md) (where applicable)
- [-] Update [Documentation](../website/docs/introduction.md) (where applicable)

[Testing] Use Kotlin Test

---

README.md
forge-core/src/main/kotlin/io/github/hellocuriosity/ModelForge.kt
forge-core/src/main/kotlin/io/github/hellocuriosity/providers/UShortProvider.kt
forge-core/src/test/kotlin/io/github/hellocuriosity/providers/UShortProviderTest.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/Assert.kt
forge-test-utils/src/main/kotlin/io/github/hellocuriosity/TestObject.kt
website/docs/introduction.md
website/docs/supported-types/ushort.md
website/docs/supported-types/uuid.md

This adds auto-generation for `UShort`s.

[Feature] UShort Provider

---

forge-core/build.gradle.kts

This aligns the environment variable to reflect a token instead of a password.

[Fix] Use Token for Publishing

---

README.md
website/docs/changelog.md
website/docs/getting-started/gradle-dependency.md
website/docs/introduction.md
website/docs/supported-types/ubyte.md
website/docs/supported-types/uint.md
website/docs/supported-types/ulong.md
website/docs/supported-types/ushort.md

This prepares the release for version `1.5.0`.

[Prepare] Release Version 1.5.0

---

.github/workflows/main.yml
.github/workflows/publish.yml
.gitignore
forge-core/build.gradle.kts
gradle/dependencies.versions.toml
scripts/publish.sh

This updates publishing to Maven Central.

[Fix] Publishing

---

website/docs/changelog.md

This updates the changelog to reflect support for Kotlin version `2.0.0`.

[Documentation] Update Changelog to Reflect Kotlin 2.0.0 Info

---

.github/workflows/auto-labeling.yml

This simplifies the auto-labeling workflow using [Auto Labeler](https://github.com/hopeman15/auto-labeler).

[CI/CD] Simplify Auto Labeling

---

.github/workflows/auto-labeling.yml

[Housekeeping] Use Labelicious

---

.github/workflows/publish.yml
forge-core/build.gradle.kts

This re-enables snapshot publishing, and disables signing for maven local.

[CI/CD] Publish Snapshots
